plugins { id 'com.android.application' }

android {
    namespace 'com.savion.skydivecompanion'
    compileSdk 35

    defaultConfig {
        applicationId 'com.savion.skydivecompanion'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '2.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release { minifyEnabled false }
    }
}
