package com.savion.skydivecompanion;

import android.Manifest;import android.app.*;import android.app.PendingIntent;import android.content.*;import android.content.pm.PackageManager;import android.hardware.*;import android.location.*;import android.media.*;import android.os.*;import android.speech.tts.TextToSpeech;import java.text.*;import java.util.*;

public class DiveService extends Service implements SensorEventListener,LocationListener,TextToSpeech.OnInitListener{
 SensorManager sm;Sensor pressure;LocationManager lm;Location lastLocation;TextToSpeech tts;AudioManager audio;float p=-1,groundP=-1;boolean baselineReady=false,tracking=false,voice=true,duck=true;long started,lastSample,lastStatus,lastVoice;double lastAgl=0,lastAlt=0,maxAlt=0,maxDescent=0;String state="GROUND";ArrayList<String> track=new ArrayList<>();HashSet<Integer> spoken=new HashSet<>();final String STATUS="status",ALERT="alerts",WATCH="watch";final int ID=701;Handler h=new Handler(Looper.getMainLooper());ArrayList<Float> pressureSamples=new ArrayList<>();double filteredP=-1;

 public int onStartCommand(Intent i,int flags,int startId){
  if(i!=null&&"WATCH_TEST_NOTIFICATION".equals(i.getAction())){createChannels();sendWatchTest();return START_NOT_STICKY;}
  if(i!=null&&"START_TRACKING".equals(i.getAction())){voice=i.getBooleanExtra("voice",true);duck=i.getBooleanExtra("duck",true);startTracking();return START_NOT_STICKY;}
  return START_NOT_STICKY;
 }
 void startTracking(){if(tracking)return;tracking=true;started=System.currentTimeMillis();state="GROUND";createChannels();startForeground(ID,statusNote("GROUND TRACKING • calibration active"));sm=(SensorManager)getSystemService(SENSOR_SERVICE);pressure=sm.getDefaultSensor(Sensor.TYPE_PRESSURE);if(pressure!=null)sm.registerListener(this,pressure,SensorManager.SENSOR_DELAY_GAME);lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,500,0.5f,this);}catch(Exception ignored){}audio=(AudioManager)getSystemService(AUDIO_SERVICE);tts=new TextToSpeech(this,this);h.postDelayed(this::finishCalibration,5000);}
 void finishCalibration(){if(pressureSamples.size()>10){double sum=0;for(float x:pressureSamples)sum+=x;groundP=(float)(sum/pressureSamples.size());filteredP=groundP;baselineReady=true;alert("CALIBRATED",String.format(Locale.US,"Ground baseline %.2f hPa. AGL zeroed.",groundP),false);}}
 void createChannels(){if(Build.VERSION.SDK_INT>=26){NotificationChannel a=new NotificationChannel(STATUS,"Jump status",NotificationManager.IMPORTANCE_LOW);a.setSound(null,null);a.enableVibration(false);NotificationChannel b=new NotificationChannel(ALERT,"Jump alerts",NotificationManager.IMPORTANCE_HIGH);b.setDescription("Only event and altitude alerts");NotificationChannel w=new NotificationChannel(WATCH,"Watch checks",NotificationManager.IMPORTANCE_HIGH);getSystemService(NotificationManager.class).createNotificationChannel(a);getSystemService(NotificationManager.class).createNotificationChannel(b);getSystemService(NotificationManager.class).createNotificationChannel(w);}}
 Notification statusNote(String s){return new Notification.Builder(this,STATUS).setContentTitle("SkyDive Companion").setContentText(s).setSmallIcon(android.R.drawable.ic_menu_compass).setOngoing(true).build();}
 void updateStatus(String s){getSystemService(NotificationManager.class).notify(ID,statusNote(s));}
 void alert(String title,String text,boolean speak){Notification n=new Notification.Builder(this,ALERT).setContentTitle(title).setContentText(text).setSmallIcon(android.R.drawable.ic_menu_compass).setAutoCancel(true).setOnlyAlertOnce(true).build();getSystemService(NotificationManager.class).notify((int)(System.currentTimeMillis()%100000),n);if(speak&&voice)say(text);}
 void sendWatchTest(){Intent ack=new Intent(this,WatchTestReceiver.class);ack.setAction("com.savion.skydivecompanion.WATCH_ACK");PendingIntent pi=PendingIntent.getBroadcast(this,911,ack,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(this,WATCH).setContentTitle("SkyDive Companion Watch Check").setContentText("Confirm the Watch notification is visible.").setSmallIcon(android.R.drawable.ic_menu_compass).setAutoCancel(true).addAction(new Notification.Action.Builder(null,"WATCH CHECK PASSED",pi).build()).build();getSystemService(NotificationManager.class).notify(911,n);}
 void say(String text){if(tts==null)return;long now=System.currentTimeMillis();if(now-lastVoice<1200)return;lastVoice=now;AudioAttributes attrs=new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ASSISTANCE_ACCESSIBILITY).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build();tts.setAudioAttributes(attrs);if(duck&&Build.VERSION.SDK_INT>=26){AudioFocusRequest req=new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK).setAudioAttributes(attrs).setWillPauseWhenDucked(false).build();audio.requestAudioFocus(req);tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"jump"+now);h.postDelayed(()->audio.abandonAudioFocusRequest(req),Math.max(1600,text.length()*55L));}else tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"jump"+now);}

 public void onSensorChanged(SensorEvent e){if(!tracking||e.sensor.getType()!=Sensor.TYPE_PRESSURE)return;float raw=e.values[0];pressureSamples.add(raw);if(pressureSamples.size()>60)pressureSamples.remove(0);if(filteredP<0)filteredP=raw;filteredP=filteredP*0.92+raw*0.08;long now=System.currentTimeMillis();
  if(!baselineReady){sendStatus(0,0,0,filteredP);return;}
  double pa=44330*(1-Math.pow(filteredP/1013.25,.1903));double agl=44330*(1-Math.pow(filteredP/groundP,.1903));if(Math.abs(agl)<1.5)agl=0;if(agl<0)agl=0;
  double fpm=0;if(lastSample>0&&now>lastSample)fpm=(agl-lastAgl)*60000.0/(now-lastSample);lastAgl=agl;lastAlt=pa;lastSample=now;maxAlt=Math.max(maxAlt,pa);maxDescent=Math.min(maxDescent,fpm);record(pa,agl,fpm);detectState(agl,fpm);if((state.equals("FREEFALL")||state.equals("CANOPY"))&&now-lastVoice>900)alerts(agl);if(now-lastStatus>500){lastStatus=now;sendStatus(pa,agl,fpm,filteredP);}}
 void sendStatus(double pa,double agl,double fpm,double hp){Intent x=new Intent("com.savion.skydivecompanion.STATUS");x.putExtra("alt",pa);x.putExtra("agl",agl);x.putExtra("fpm",fpm);x.putExtra("pressure",hp);x.putExtra("state",state);x.putExtra("timer",formatElapsed());sendBroadcast(x);updateStatus(state+" • AGL "+String.format(Locale.US,"%.0f",agl)+" ft");}
 String formatElapsed(){long s=Math.max(0,(System.currentTimeMillis()-started)/1000);return String.format(Locale.US,"%02d:%02d",s/60,s%60);}
 void detectState(double agl,double fpm){if(state.equals("GROUND")){if(fpm>250&&agl>100){state="AIRCRAFT";event("AIRCRAFT ASCENT");}}else if(state.equals("AIRCRAFT")){if(fpm<-1200){state="FREEFALL";event("EXIT DETECTED");}}else if(state.equals("FREEFALL")){if(fpm>-1800&&fpm<300){state="CANOPY";event("CANOPY DETECTED");}}else if(state.equals("CANOPY")){if(agl<120&&Math.abs(fpm)<700){state="POST-LANDING";event("LANDING DETECTED");h.postDelayed(this::finishJump,120000);}}}
 void event(String s){alert(s,s,false);}
 void alerts(double agl){int[] bands={10000,9000,8000,7000,6000,5000,4000,3000,2000,1500,1000,500};for(int b:bands)if(agl<=b&&!spoken.contains(b)){spoken.add(b);alert("ALTITUDE",b+" feet",true);break;}}
 void record(double pa,double agl,double fpm){if(lastSample==0)return;long now=System.currentTimeMillis();if(track.size()>0){String prev=track.get(track.size()-1);try{long t=Long.parseLong(prev.substring(0,prev.indexOf(',')));if(now-t<700)return;}catch(Exception ignored){}}String loc="";if(lastLocation!=null)loc=String.format(Locale.US,"%.7f,%.7f",lastLocation.getLatitude(),lastLocation.getLongitude());track.add(now+","+pa+","+agl+","+fpm+","+state+","+loc);if(track.size()>2400)track.remove(0);}
 public void onLocationChanged(Location l){lastLocation=l;}
 void finishJump(){if(!tracking)return;tracking=false;String date=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date(started));String summary=date+" | max PA "+String.format(Locale.US,"%.0f",maxAlt)+" ft | max descent "+String.format(Locale.US,"%.0f",Math.abs(maxDescent))+" ft/min | track points "+track.size();getSharedPreferences("jumpLog",0).edit().putString("last",summary).putString("track",android.text.TextUtils.join("\n",track)).apply();stopSelf();}
 public void onInit(int status){if(status==TextToSpeech.SUCCESS){tts.setLanguage(Locale.US);tts.setSpeechRate(1.05f);}}
 public void onAccuracyChanged(Sensor s,int a){}public void onProviderEnabled(String s){}public void onProviderDisabled(String s){}public void onStatusChanged(String s,int a,Bundle b){}
 public void onDestroy(){if(sm!=null)sm.unregisterListener(this);if(lm!=null)lm.removeUpdates(this);if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
 public IBinder onBind(Intent i){return null;}
}
